/**
 * English (en) translation of the resource-centre guides.
 * The `slug` values are stable across locales (URLs).
 */
export interface Guide {
  slug: string
  title: string
  intro: string
  steps: readonly string[]
}

export const GUIDES: readonly Guide[] = [
  {
    slug: 'story-builder-export',
    title: 'Create a selection and export it from Story Builder',
    intro:
      'Steps based on the Story Builder interface: conversations, the «Ask KAI» field, playlist, clip cards, the «Refine» button and export via «Export» with EDL, XML and OTIO options.',
    steps: [
      'Open Story Builder and create a new conversation or reopen an existing conversation from the project.',
      'Type your query into the «Ask KAI» field using natural language. For example, you can ask for a situation, a topic, a statement or a specific narrative moment.',
      'Review the response generated by KAI and the playlist of clips it finds. Check the video, timecodes and the summary information of the selection before continuing.',
      'Adjust the selection from the clip cards: review the descriptions, remove what does not fit and reorder the fragments when you need to build a narrative sequence.',
      'Use «Refine» to sharpen the search without losing the context of the conversation.',
      'When the selection is ready, use «Export» and pick one of the options available in the interface, such as EDL, XML or OTIO, according to the configured editing workflow.',
      'Continue the edit in your editor using the exported selection.',
    ],
  },
  {
    slug: 'premiere-panel',
    title: 'Work with KAI from the Adobe Premiere Pro panel',
    intro:
      'The available documentation describes the KAI panel for Adobe Premiere Pro as an extension of the editing workflow, with access to project conversations, selection versions, integrated chat and the ability to insert AI-identified clips into the timeline.',
    steps: [
      'With the KAI panel already configured in Adobe Premiere Pro, open the conversations associated with the project from the panel sidebar.',
      'Select a conversation or a previously generated playlist to reuse searches and selections without rebuilding the work from scratch.',
      'Review the available versions of a selection, such as the original or its refinements, to compare narrative alternatives before deciding.',
      'Use «Chat» mode to request new criteria, adjust a search or refine the selection based on the editing context.',
      'Select the KAI-identified clips you want to use and drop them into the timeline from within the editing environment itself.',
    ],
  },
]

/** Returns the guide whose slug matches, or undefined if it does not exist. */
export function findGuideBySlug(slug: string | undefined): Guide | undefined {
  return GUIDES.find((guide) => guide.slug === slug)
}
